# docker-compose.yml

# how to build:
# docker-compose up --build

version: '2'

# =====================================
#               SERVICES
# =====================================

services:

  # =====================================
  #                 HDFS
  # =====================================

  # =====================================
  #                END HDFS
  # =====================================

  # =====================================
  #          HIVE (Data Warehouse)
  # =====================================

  # Commands:
  # enter bash as root user:
  # docker exec -it -u 0 hiveserver2 bash
  # docker exec -it hiveserver2 bash
  # beeline -u jdbc:hive2://0.0.0.0:10000 -n root -p root
  # start at the same process:
  # beeline -u jdbc:hive2://
  # show databases;
  # create database bde_dw;
  # use bde_dw;
  # show tables;
  # create table test (id int, name string);
  # show tables;
  # insert into test values (1, 'test');
  # select * from test;
  # drop table test;
  # drop database bde_dw;

  metastore-db:
    image: postgres:15
    restart: unless-stopped
    container_name: metastore-db
    hostname: metastore-db
    environment:
      POSTGRES_DB: 'metastore_db'
      POSTGRES_USER: 'hive'
      POSTGRES_PASSWORD: 'hive'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - '5432:5432'
    volumes:
      - metastore-db:/var/lib/postgresql
    networks:
      bigdata_net:
        ipv4_address: 172.16.1.2

  metastore:
    image: lucastrubiano/hive:hive_3_1_3__hadoop_3_3_5__tez_0_9_2
    depends_on:
      - metastore-db
    restart: unless-stopped
    container_name: metastore
    hostname: metastore
    environment:
      DB_DRIVER: postgres
      SERVICE_NAME: 'metastore'
      SERVICE_OPTS: '-Xmx1G -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
                     -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://172.16.1.2:5432/metastore_db
                     -Djavax.jdo.option.ConnectionUserName=hive
                     -Djavax.jdo.option.ConnectionPassword=hive'
      IS_RESUME: 'true' # set to false (for the first time) and true (after the first time)
    ports:
      - '9083:9083'
    volumes:
      - warehouse:/opt/hive/data/warehouse
      - ./docker_shared_folder/drivers/postgresql-42.5.2.jar:/opt/hive/lib/postgresql-42.5.2.jar
      - ./docker_shared_folder/hive_conf/hive-site.xml:/opt/hive/conf/hive-site.xml
    networks:
      bigdata_net:
        ipv4_address: 172.16.1.3

  hiveserver2:
    image: lucastrubiano/hive:hive_3_1_3__hadoop_3_3_5__tez_0_9_2
    depends_on:
      - metastore
    restart: unless-stopped
    container_name: hiveserver2
    hostname: hiveserver2
    environment:
      HIVE_SERVER2_THRIFT_PORT: 10000
      SERVICE_OPTS: '-Xmx1G -Dhive.metastore.uris=thrift://metastore:9083'
      IS_RESUME: 'true'
      SERVICE_NAME: 'hiveserver2'
    # command: "mkdir -p /home/hive && chown -R hive:hive /home && chmod -R 777 /home"
    ports:
      - '10000:10000'
      - '10002:10002'
    volumes:
      - warehouse:/opt/hive/data/warehouse
      - ./docker_shared_folder/drivers/postgresql-42.5.2.jar:/opt/hive/lib/postgresql-42.5.2.jar
      - ./docker_shared_folder/hive_conf/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./docker_shared_folder/hive_conf/hive-site.xml:/opt/hive/conf/hive-site.xml
    networks:
      bigdata_net:
        ipv4_address: 172.16.1.4

  # =====================================
  #               END HIVE
  # =====================================
  
  # =====================================
  #          Postgres (BDE OLTP)
  # =====================================

  postgres_bde:
    image: postgres:15
    container_name: postgres_bde
    hostname: postgres_bde
    ports:
      - "5433:5433"
    volumes:
      - ./docker_shared_folder/bde:/var/lib/postgresql/data
    environment:
      # - POSTGRES_HOST=postgres_bde
      - POSTGRES_USER=prod
      - POSTGRES_PASSWORD=prod
      - POSTGRES_DB=bde
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    command: "-p 5433"
    networks:
      bigdata_net:
        ipv4_address: 172.16.1.5

  # =====================================
  #             END Postgres
  # =====================================

  # =====================================
  #                 HUE
  # =====================================

  # HUE (Hadoop User Experience)
  hue:
    image: gethue/hue:4.11.0 # 20230102-140101 #4.11.0 #gethue/hue:4.6.0 # gethue/hue:20230102-140101 # 4.11.0 # 20230505-140101
    hostname: hue
    container_name: hue
    dns: 8.8.8.8
    ports:
      - "8888:8888"
    environment:
      SERVICE_PRECONDITION: "postgres_bde:5433" #"hdfs-namenode:50070 hdfs-datanode:50075 hive-metastore-postgresql:5432 yarn-resourcemanager:8088 hive-metastore:9083 database-dbe:5433"
    volumes:
      - ./docker_shared_folder/hue.ini:/usr/share/hue/desktop/conf/z-hue.ini
    depends_on:
      - postgres_bde
    networks:
      bigdata_net:
        ipv4_address: 172.16.1.6

  # =====================================
  #                END HUE
  # =====================================

# =====================================
#            END SERVICES
# =====================================


# =====================================
#               VOLUMES
# =====================================
volumes:
  metastore-db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./docker_shared_folder/metastore_db
  warehouse:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./docker_shared_folder/warehouse

# =====================================
#               NETWORKS
# =====================================

networks:
  bigdata_net: # Name of the network
    ipam: # IP Address Management
      driver: default
      config:
        - subnet: 172.16.0.0/16 # Subnet
        # 172.16.1.0 is the default subnet for docker
        # 16 is the number of bits used for the network